### ISSUE TITLE
getting this error after set variables & run python app.py

### ISSUE THREAD

**Issue by todokku** [ravgeetdhillon/musica#1]
getting this error after set variables & run python app.py
os : win 10 
python : 3.7

`Traceback (most recent call last):
  File "app.py", line 222, in <module>
    app()
  File "app.py", line 185, in app
    files = get_files(creds=drive_creds)
  File "app.py", line 37, in get_files
    drive_service = build('drive', 'v3', credentials=creds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\discovery.py", line 231, in build
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\discovery.py", line 223, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\googleapiclient\discovery.py", line 276, in _retrieve_discovery_doc
    raise HttpError(resp, content, uri=actual_url)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/discovery/v1/apis/drive/v3/rest returned "Forbidden">`

**Comment by ravgeetdhillon** [comment]
Hello @todokku 

These are some reasons for getting the 403 Forbidden error.
https://cloud.google.com/storage/docs/json_api/v1/status-codes#403_Forbidden

I hope that you have followed these steps to get the functionality working:

1. Create a new project in the Google Developer Console.
2. Enable the Google Drive API and Youtube Data API.
3. Create your API credentials and get your `secret id` and `secret key`.
4. Authorize these two scopes: scope for [Google Drive](https://github.com/ravgeetdhillon/musica/blob/master/src/variables.py#L17) and scope for [Youtube API](https://github.com/ravgeetdhillon/musica/blob/master/src/variables.py#L22).
5. Go to [Google Oauth Playground](https://developers.google.com/oauthplayground/) and get your refresh token.
6. You are set to go.

> Note:
> If you are using multiple GMAIL accounts, like one for your Youtube channel and another one for your Google drive, you need to get two refresh tokens, for one each.

**Comment by todokku** [comment]
Hi @Ravgeet ,
after make variables exact on your 6 steps , 
giving same error , bro if its possible test it on windows 10 os , i think variables.py not detect from app.py & must be set in path ?!
please help me , so recommended your code 
waiting your response 
finest regards

**Comment by ravgeetdhillon** [comment]
The code is cross-platform. The error indicates that either you haven't set the right variable, or they are not in the path or you don't have the permissions to access APIs.

**Comment by ravgeetdhillon** [comment]
@todokku Are you still facing the error? I am closing the issue for now.
